### ISSUE TITLE
beta release checklist

### ISSUE THREAD

**Issue by frostu8** [frostu8/among-us#1]
Before I open contributions, I want to complete an engine for this, so people can instead contribute to those foundations. This is a list of tasks that needs to be done before I consider `among-us` good for contributions and beta releases.
- [ ] Collision systems.
- [ ] Application-layer UDP networking.
- [ ] Task logic and networking.
- [ ] Basic gameplay logic and networking.
- [ ] Graphics.
- [ ] Resource collections for audio and images.
- [ ] Client accessibility.

While contributions are not welcome, suggestions and conversations are encouraged. I'm one guy juggling heavy schoolwork and work at home, so it's hard for me to come across free time, let alone time I'd rather be programming than relaxing.

**Comment by IJustDev** [comment]
Is this still up to date? Would like to work on this project.

**Comment by frostu8** [comment]
> Is this still up to date? Would like to work on this project.

Kind of. You can make PRs and I'll accept them. I just have a collision system and some lame netcode down.
